name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: development
      DEBUG: "True"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Create .env.development file
        run: |
          echo "ENV=development" >> .env.development
          echo "DEBUG=True" >> .env.development
          echo "LOG_LEVEL=DEBUG" >> .env.development
          echo "GROQ_API_KEY=dummy_key_for_ci" >> .env.development
          echo "GROQ_MODEL_NAME=llama-3-70b" >> .env.development
          echo "LLM_PROVIDER=groq" >> .env.development

      - name: Run tests
        run: |
          pytest -s
